### ISSUE TITLE
Gibt keine zornige Biene mehr :( (Bad Gateway error 502 von gograph.com)

### ISSUE THREAD

**Issue by laffiie** [mammatus95/Synopstalking#31]
https://github.com/mammatus95/Synopstalking/blob/85db941901011c64215bdd191556994c3c4c5f43/webcode/control.php#L1305C36-L1305C108

**Comment by mammatus95** [comment]
Danke werde was neues suchen

**Comment by mammatus95** [comment]
[Angry bee](https://www.reddit.com/media?url=https%3A%2F%2Fpreview.redd.it%2Foxyqpcs96mg31.jpg%3Fauto%3Dwebp%26s%3D004a439f920e0e01e3216083b75d56542f66cbe6)

**Comment by mammatus95** [comment]
[url](https://banner2.cleanpng.com/20191004/eaa/transparent-bumblebee-5da391088c8718.8444133415710005845756.jpg)
